---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testbranch-testteam-1
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    servicenowincidentid: test000001
    owner: ahussey-redhat
  finalizers:
    - "resources-finalizer.argocd.argoproj.io/background"
spec:
  destination:
    namespace: testbranch-testteam
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: environments/testbranch-testteam-1
    repoURL: >-
      https://github.com/ahussey-redhat/aap-as-a-service-gitops.git
    targetRevision: main
  syncPolicy:
    preserveResourcesOnDeletion: false
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: "openshift-gitops"
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
