apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: testbranch-testteam
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
resources:
  - aap-instance/overlays/stable-2.4
