---
apiVersion: eda.ansible.com/v1alpha1
kind: EDA
metadata:
  name: d9d0a971c0a80a641c20b13d99a48576-5898f18a3b700300d901655593efc43a-1-eda
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  route_tls_termination_mechanism: Edge
  ingress_type: Route
  route_host: 5898f18a3b700300d901655593efc43a-eda-1.apps.cluster-ljlsm.ljlsm.sandbox1851.opentlc.com
  loadbalancer_port: 80
  no_log: true
  image_pull_policy: IfNotPresent
  ui:
    replicas: 1
  set_self_labels: true
  api:
    gunicorn_workers: 2
    replicas: 1
  redis:
    replicas: 1
  admin_user: admin
  loadbalancer_protocol: http
  worker:
    replicas: 2
  automation_server_url: https://5898f18a3b700300d901655593efc43a-controller-1.apps.cluster-ljlsm.ljlsm.sandbox1851.opentlc.com
