---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: d9d0a971c0a80a641c20b13d99a48576-f90df054133002003ff3691c2c6a5e11-1
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    servicenowincidentid: 214716551badf110e07d43bdcc4bcb3d
    owner: undefined
  finalizers:
    - "resources-finalizer.argocd.argoproj.io/background"
spec:
  destination:
    namespace: d9d0a971c0a80a641c20b13d99a48576-f90df054133002003ff3691c2c6a5e11
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: environments/d9d0a971c0a80a641c20b13d99a48576-f90df054133002003ff3691c2c6a5e11-1
    repoURL: >-
      https://github.com/ahussey-redhat/aap-as-a-service-gitops.git
    targetRevision: main
  syncPolicy:
    preserveResourcesOnDeletion: false
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: "openshift-gitops"
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
