---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: d9d0a971c0a80a641c20b13d99a48576-5898f18a3b700300d901655593efc43a-1
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    servicenowincidentid: REQ0010103
    owner: 7905d3101b543110d8bf10ab274bcbcb
  finalizers:
    - "resources-finalizer.argocd.argoproj.io/background"
spec:
  destination:
    namespace: d9d0a971c0a80a641c20b13d99a48576-5898f18a3b700300d901655593efc43a
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: environments/d9d0a971c0a80a641c20b13d99a48576-5898f18a3b700300d901655593efc43a-1
    repoURL: >-
      https://github.com/ahussey-redhat/aap-as-a-service-gitops.git
    targetRevision: main
  syncPolicy:
    preserveResourcesOnDeletion: false
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: "openshift-gitops"
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
