---
apiVersion: eda.ansible.com/v1alpha1
kind: EDA
metadata:
  name: ${BRANCH_NAME}-${TEAM_NAME}-${INSTANCE_ID}-hub
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  route_tls_termination_mechanism: Edge
  ingress_type: Route
  route_host: ${TEAM_NAME}-eda-${INSTANCE_ID}.${APP_URL}
  loadbalancer_port: 80
  no_log: true
  image_pull_policy: IfNotPresent
  ui:
    replicas: 1
  set_self_labels: true
  api:
    gunicorn_workers: 2
    replicas: 1
  redis:
    replicas: 1
  admin_user: admin
  loadbalancer_protocol: http
  worker:
    replicas: 2
  automation_server_url: https://${TEAM_NAME}-controller-${INSTANCE_ID}.${APP_URL}

