---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  annotations:
    cert-manager.io/issuer-kind: ClusterIssuer
    cert-manager.io/issuer-name: letsencrypt-sandbox
  name: ${BRANCH_NAME}-${TEAM_NAME}-${INSTANCE_ID}-hub
  labels:
    app.kubernetes.io/managed-by: hub-operator
    app.kubernetes.io/instance: ${BRANCH_NAME}-${TEAM_NAME}-${INSTANCE_ID}
    app.kubernetes.io/part-of: ${BRANCH_NAME}-${TEAM_NAME}-${INSTANCE_ID}-hub
spec:
  host: ${TEAM_NAME}-hub-${INSTANCE_ID}.${APP_URL}
  to:
    kind: Service
    name: ${BRANCH_NAME}-${TEAM_NAME}-${INSTANCE_ID}-hub-api-svc
    weight: 100
  port:
    targetPort: api-24817
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
