apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
resources:
  - operatorgroup.yml
  - subscription.yml
  - rolebinding.yml
  - controller.yml
  - controller_route.yml
  - hub.yml
  - hub_route.yml
  - eda.yml
  - eda_route.yml