apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - operatorgroup.yml
  - subscription.yml
  - instance.yml
  - rolebinding.yml
  - controller.yml
  - controller_route.yml
  - hub.yml
  - eda.yml