kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployer-and-pipeline-admin
  namespace: ${BRANCH_NAME}-${TEAM_NAME}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
subjects:
  - kind: ServiceAccount
    name: deployer
    namespace: aap-as-a-service
  - kind: ServiceAccount
    name: pipeline
    namespace: aap-as-a-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
