---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: <change-me>
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    namespace: <change-me>
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: aap-instance/overlays/stable-2.4
    repoURL: >-
      https://github.com/ahussey-redhat/aap-as-a-service-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true