apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: <change-me>
metadata:
  name: kustomization-file
resources:
  - ../aap-instance/overlays/stable-2.4
patches:
  - target:
      kind: AutomationController
      name: <change-me>
    patch: |-
      - op: replace
        path: /metadata/name
        value: 'stable-2.4'